In [4]:
import numpy as np

a = np.arange(1, 13)
a= a.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[15 18 21 24]
[10 26 42]


In [10]:
temp = np.array= [1, 4, 5, 6, 7, 3, 8]

alerts = temp[temp.mean() >= temp]
print(alerts)

AttributeError: 'list' object has no attribute 'mean'

In [7]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
