In [2]:
import numpy as np

nums = [1, 2, 3]
result = [n * 2 for n in nums]

arr = np.array([1, 2, 3])
result2 = arr*2
print(result2)

[2 4 6]


In [4]:
a = np.array([1, 2, 3], dtype=float)
b = np.zeros((2, 3))
c = np.arange(1, 10, 2)
d = np.linspace(0, 1, 5)
print(a)
print(b)
print(c)
print(d)

[1. 2. 3.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('차원: ', arr.ndim)
print('모양: ', arr.shape)
print('전체 개수: ', arr.size)
print('자료형: ', arr.dtype)
print('개수: ', arr.itemsize)

차원:  2
모양:  (2, 3)
전체 개수:  6
자료형:  int64
자료형:  8


In [5]:
arr = np.arange(12)
mat = arr.reshape(3, 4)
print(mat)

flat = mat.flatten()
print(flat)

auto = arr.reshape(2, -1)
print(auto.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(2, 6)


In [12]:
arr = np.array(
    [[10, 20, 30],
     [40, 50, 60],
     [70, 80, 90]])
print(arr[0])
print(arr[1, 2])
print(arr[:, 0])
print(arr[0:2, 1:3])
print(arr[::-1])

[10 20 30]
60
[10 40 70]
[[20 30]
 [50 60]]
[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [10]:
temps = np.array([21.2, 22.1, 24.0, 30.5, 25.2])

mask = temps >= 24
warning = temps[mask]
print(warning)

print(temps[temps >= 24])

temps[temps >= 30] = 30.0
print(temps)

[24.  30.5 25.2]
[24.  30.5 25.2]
[21.2 22.1 24.  30.  25.2]


In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a * 2)

mat = np.array([[1,2,3],[4,5,6]])
row = np.array([10, 20, 30])
print(mat+row)

[11 22 33]
[2 4 6]
[[11 22 33]
 [14 25 36]]


In [14]:
data = np.array([[20, 60],
                 [22, 55],
                 [25, 58]])
print('전체 평균:', data.mean())
print('열별 평균(axis=0):', data.mean(axis=0))
print('행별 평균(axis=1):', data.mean(axis=1))
print('가장 더운 센서:', np.argmax(data[:, 0]))

전체 평균: 40.0
열별 평균(axis=0): [22.33333333 57.66666667]
행별 평균(axis=1): [40.  38.5 41.5]
가장 더운 센서: 2


In [16]:
temps = np.array([21.5, 30.2, 26.1, 33.4, 19.8])

print('배열:', temps)
print('차원:', temps.ndim)      # 1
print('모양:', temps.shape)     # (5,)
print('자료형:', temps.dtype)   # float64

배열: [21.5 30.2 26.1 33.4 19.8]
차원: 1
모양: (5,)
자료형: float64


In [15]:
raw = np.arange(10)
log = raw.reshape(5, 2)

print(log)
print('시점 수:', log.shape[0])
print('센서 수:', log.shape[1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
시점 수: 5
센서 수: 2


In [17]:
temps = np.array([21.5, 30.2, 26.1, 33.4, 19.8])

alerts = temps[temps >= 30]
print('경고 값:', alerts)

count = (temps >= 30).sum()
print('경고 건수:', count)

경고 값: [30.2 33.4]
경고 건수: 2


In [20]:
data = np.array([[20, 60],
                 [22, 55],
                 [31, 58]])

col_mean = data.mean(axis=0)
row_max = data.max(axis=1)

print('열 평균:', col_mean)
print('행 최댓값:', row_max)

열 평균: [24.33333333 57.66666667]
행 최댓값: [60 55 58]


In [19]:
celsius = np.array([20.0, 25.0, 30.0, 35.0])

fahrenheit = celsius * 9 / 5 + 32

print('섭씨:', celsius)
print('화씨:', fahrenheit)

섭씨: [20. 25. 30. 35.]
화씨: [68. 77. 86. 95.]
